name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install  # ou une autre commande selon votre gestionnaire de paquets

    - name: Build
      run: |
        npm run build  # changez cela en fonction de votre script de build

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.1.0
      with:
        publish-dir: ./dist
        github-token: ${{ secrets.GITHUB_TOKEN }}
        publish-dir: ./build
        netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}