name: MAIN

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate report
        run: |
          npm test -- --reporter=json --outputFile=test-results.json || true

      - name: Debug test results
        run: ls -lah && cat test-results.json || echo "File is missing"

      - name: Update README with test results
        run: |
          if [ -f test-results.json ]; then
            PASSED=$(jq '.summary.passed' test-results.json)
            FAILED=$(jq '.summary.failed' test-results.json)
            TOTAL=$(jq '.summary.total' test-results.json)
            echo "## Test Results" > test-summary.txt
            echo "**Tests passed:** $PASSED" >> test-summary.txt
            echo "**Tests failed:** $FAILED" >> test-summary.txt
            echo "**Total tests:** $TOTAL" >> test-summary.txt
            cat test-summary.txt >> README.md
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add README.md
            git commit -m "Update README with test results"
            git push origin master
          else
            echo "Test results file not found, skipping README update."
          fi