name: Run tests and update README

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate report
        run: npm test -- --environment node --reporter json > test-results.json

      - name: Extract test results
        run: |
          PASSED=$(jq '.summary.passed' test-results.json)
          FAILED=$(jq '.summary.failed' test-results.json)
          TOTAL=$(jq '.summary.total' test-results.json)
          echo "Tests passed: $PASSED, Tests failed: $FAILED, Total tests: $TOTAL" > test-summary.txt

      - name: Update README with test results
        run: |
          TEST_RESULTS=$(cat test-summary.txt)
          echo "## Test Results" >> README.md
          echo "$TEST_RESULTS" >> README.md
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with test results"
          git push origin master
