name: MAIN

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --reporter json --environment=node > test-results.json

      - name: Upload test results as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results.json

      - name: Display test results
        run: cat test-results.json
